core/urls.py
from flask import Blueprint

from core.views import feedback, error_403, error_404, error_500


core = Blueprint("core", __name__, template_folder="templates", static_folder="static")
core.add_url_rule("/feedback", "feedback", feedback, methods=["GET", "POST"])
core.register_error_handler(403, error_403)
core.register_error_handler(404, error_404)
core.register_error_handler(500, error_500)

core/views.py
from flask import render_template, request, redirect, url_for

from core.forms import FeedbackForm


def error_403(err):
    return render_template("core/403.html"), 403


def error_404(err):
    return render_template("core/404.html"), 404


def error_500(err):
    return render_template("core/500.html"), 500


def feedback():
    form = FeedbackForm()
    if form.validate_on_submit():
        email = request.form["email"]
        text = request.form["text"]
        print(email)
        print(text)
        return redirect(url_for("posts.index"))
    return render_template("core/feedback.html", form=form)

templates/includes/custom_paginator.html
<!-- templates/includes/custom_paginator.html -->

{% if page_obj.iter_pages != 1 %}
    <nav aria-label="Page navigation" class="my-5">
        <ul class="pagination">
            {% if page_obj.has_prev %}
                <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.prev_num }}">
                      Предыдущая
                    </a></li>
            {% endif %}


                {% for p in page_obj.iter_pages() %}
                    {% if p == page_obj.page %}
                      <li class="page-item active">
                        <span class="page-link">{{ p }}</span>
                      </li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ p }}">{{ p }}</a> </li>
                    {% endif %}
                {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_num }}">
                    Следующая
                </a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.pages }}">
                    Последняя
                </a></li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

templates/includes/footer.html
<!-- templates/posts/includes/footer.html -->

<div class="footer-copyright text-center py-3">
  © 2023 Copyright
    <p>
      <span style="color:red">Ya</span>tube
    </p>
</div>

templates/includes/form.html
<!-- templates/posts/includes/form.html -->


<div class="card">
    <div class="card-header">
        {% if not header %}
            {% if not is_comment %}
                {% if is_edit %}
                    Редактировать пост
                {% else %}
                    Новый пост
                {% endif %}
            {% else %}
                {% if is_edit %}
                    Редактировать комментарий
                {% else %}
                    Новый комментарий
                {% endif %}
            {% endif %}
        {% else %}
            {{ header }}
        {% endif %}
    </div>
    <div class="card-body">
        <form method="post" enctype="multipart/form-data" action="">
            {{ form.hidden_tag() }}
              {% for field in form if field.name not in ['csrf_token', 'submit'] -%}
                <div class="form-group row my-3" aria-required="true">
                  <label>
                    {{ field.label(class='control-label') }}
                        <span class="required text-danger">*</span>
                  </label>
                  <div>
                    {% if field.errors %}
                      {{ field(class="invalid") }}
                      {% for e in field.errors %}
                        {{ e }}
                      {% endfor %}
                    {% else %}
                      {{ field(class='form-control') }}
                    {% endif %}
                  </div>
                </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
        </form>
    </div>
</div>

templates/includes/fullpost.html
<!-- templates/posts/includes/fullpost.html -->


<h2>
    {{ post.title }}
</h2>
<ul>

  {% if not no_author %}
      <li>
        <h3>Автор: {{ post.author }}</h3>
      </li>
  {% endif %}

  <li>
    <p>Дата публикации: {{ post.created.strftime('%Y-%m-%d') }}</p>
  </li>
</ul>
<div class="tags">
    {% for tag in post.tags %}
        <a class="btn btn-primary" href="{{ url_for('posts.post_tag', tag_slug=tag.slug) }}" role="button">{{ tag.title }}</a>
    {% endfor %}
</div>
<div class="main-content">
    <p>
      {{ post.text|truncate(50, True) }}
    </p>
</div>


<p>
    <a href="{{ url_for('posts.show_post', post_slug=post.slug) }}"> Читать полностью </a>
</p>

{% if not group %}
    {% if post.group%}
      <p>
        <a href="{{ url_for('posts.post_group', group_slug=post.group.slug) }}"> Все записи группы {{ post.group.slug }} </a>
      </p>
        <p>Группа: {{ post.group }}</p>
    {% else %}
      <p> Группа отсутствует </p>
    {% endif %}
{% endif %}

templates/includes/head.html
<!-- templates/posts/includes/head.html -->

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" href="{{ url_for('static', filename='img/fav/fav.ico') }}" type="image">
<link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='img/fav/apple-touch-icon.png') }}">
<link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='img/fav/favicon-32x32.png') }}">
<link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='img/fav/favicon-16x16.png') }}">
<meta name="msapplication-TileColor" content="#000">
<meta name="theme-color" content="#ffffff">
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">

templates/includes/header.html
<!-- templates/posts/includes/header.html -->


  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{ url_for('posts.index') }}">
        <img src="{{ url_for('static', filename='img/logo.png') }}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>

      <ul class="nav nav-pills">

        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'posts:feedback' %}active{% endif %}"
             href="{{ url_for('core.feedback') }}">Обратная связь</a>
        </li>

        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
             href="{{ url_for('about.author') }}">Об авторе</a>
        </li>

        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
             href="{{ url_for('about.tech') }}">Технологии</a>
        </li>


        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
             href="{{ url_for('posts.post_create') }}">Новая запись</a>
        </li>

        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'posts:show_follows' %}active{% endif %}"
             href="{{ url_for('users.show_follows') }}">Моя лента</a>
        </li>
        <form class="d-flex" role="search" method="GET">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{ request.args.get('q', '') }}">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </ul>
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}"
             href="{{ url_for('security.logout') }}">Выйти</a>
        </li>
        {% if current_user.has_role('admin') or current_user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link link-light active" href="/admin">Админка</a>
          </li>
        {% elif current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link link-light {% if view_name  == 'posts:show_profile' %}active{% endif %}"
             href="{{ url_for('users.show_profile', user_slug=1) }}">Текущий юзер</a>
        </li>
        {% endif %}

        <li class="nav-item">
          <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}" href="{{ url_for('security.login') }}">Войти</a>
        </li>

        <li class="nav-item">
          <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}" href="{{ url_for('users.users_signup') }}">Регистрация</a>
        </li>

      </ul>

    </div>
  </nav>

templates/includes/switcher.html
<!-- templates/posts/includes/switcher.html -->

{% with request.resolver_match.view_name as view_name %}

    {% if user.is_authenticated %}
      <div class="row my-3">
        <ul class="nav nav-tabs">

          <li class="nav-item">
            <a
              class="nav-link {% if view_name == 'posts:index' %}active{% endif %}"
              href="{% url 'posts:index' %}"
            >
              Все авторы
            </a>
          </li>

          <li class="nav-item">
            <a
               class="nav-link {% if view_name == 'posts:show_follows' %}active{% endif %}"
               href="{% url 'posts:show_follows' %}"
            >
              Избранные авторы
            </a>
          </li>

        </ul>
      </div>
    {% endif %}

{% endwith %}