posts/urls.py
from flask import Blueprint

from posts.views import index, show_post, post_create, post_tag, post_group, group_list, post_edit

posts = Blueprint("posts", __name__, template_folder="templates", static_folder="static")

posts.add_url_rule("/", "index", index)
posts.add_url_rule("/posts/create", "post_create", post_create, methods=["GET", "POST"])
posts.add_url_rule("/posts/<string:post_slug>/edit", "post_edit", post_edit, methods=["GET", "POST"])
posts.add_url_rule("/posts/<string:post_slug>", "show_post", show_post)
posts.add_url_rule("/posts/tag/<string:tag_slug>", "post_tag", post_tag)
posts.add_url_rule("/posts/group/<string:group_slug>", "post_group", post_group)
posts.add_url_rule("/posts/group_list", "group_list", group_list)

posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SelectField, SelectMultipleField
from wtforms.validators import DataRequired

from models import Group, Tag


class PostCreateForm(FlaskForm):
    title = StringField("Название", validators=[DataRequired()])
    text = TextAreaField("Описание", validators=[DataRequired()])
    group = SelectField("Группа", choices=[elem.slug for elem in Group.query.all()])
    tags = SelectMultipleField("Теги", choices=[elem.slug for elem in Tag.query.all()])

posts/views.py
from flask import render_template, request, redirect, url_for
from flask_login import login_required

from app import app, db
from core.forms import FeedbackForm

from posts.forms import PostCreateForm
from models import Post, Group, User, Tag
from .utils import paginator, post_filter


def index():
    posts = post_filter(Post.query)
    return render_template("posts/index.html", page_obj=paginator(posts))

@login_required
def post_create():
    form = PostCreateForm()
    if form.validate_on_submit():
        title = request.form["title"]
        text = request.form["text"]
        group = Group.query.filter_by(slug=request.form["group"]).first()
        post = Post(title=title, text=text, group_id=group.id, author_id=1)
        for value in request.form.getlist("tags"):
            tag = Tag.query.filter_by(slug=value).first()
            post.tags.append(tag)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for("posts.show_post", post_slug=post.slug))
    return render_template("posts/creation.html", form=form)

@login_required
def post_edit(post_slug):
    post = Post.query.filter_by(slug=post_slug).first()
    if request.method == "POST":
        form = PostCreateForm(formdata=request.form, obj=post)
        # Добавить поддержку заполнения связанных полей, возможно через ModelForm
        # Добавить замену слага при изменении имени
        for elem in form.data:
            print(elem)
        form.populate_obj(post)
        db.session.commit()
        return redirect(url_for("posts.show_post", post_slug=post.slug))
    form = PostCreateForm(obj=post)
    return render_template("posts/creation.html", form=form)

@login_required
def show_post(post_slug):
    post = Post.query.filter_by(slug=post_slug).first()
    # Исправить шаблон
    return render_template("posts/show_post.html", post=post)


def group_list():
    return render_template("posts/list_of_groups.html", groups=Group.query.all())


def post_group(group_slug):
    posts = Post.query.join(Group).filter(Group.slug == group_slug)
    posts = post_filter(posts)
    return render_template("posts/index.html", page_obj=paginator(posts))


def post_tag(tag_slug):
    posts = Post.query.join(Tag, Post.tags).filter(Tag.slug == tag_slug)
    posts = post_filter(posts)
    return render_template("posts/index.html", page_obj=paginator(posts))

posts/templates/posts/creation.html
<!-- templates/posts/includes/creation.html -->

{% extends 'base.html' %}

{% block title %}
    {% if not is_comment %}
        {% if is_edit %}
            Редактирование поста
        {% else %}
            Добавление нового поста
        {% endif %}
    {% else %}
        {% if is_edit %}
            Редактирование комментария
        {% else %}
            Добавление нового комментария
        {% endif %}
    {% endif %}
{% endblock %}

{% block content %}
    <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            {% include 'includes/form.html' %}
          </div>
        </div>
    </div>
{% endblock %}

posts/templates/posts/group_list.html
<!-- templates/posts/group_list.html -->

{% extends 'base.html' %}

{% block title %}
  {% if archive %}
    Архив группы {{ group.title }}
  {% else %}
    Страница группы {{ group.title }}
  {% endif %}
{% endblock %}

{% block content %}

    {% for post in posts %}
      <article>
        {% if forloop.first %}
          <h1> {{ post.group.title }} </h1>
          <p>{{ post.group.description }}</p>
          <h2> Все доступные посты </h2>
        {% endif %}

        {% include 'includes/fullpost.html' with group=True %}

        {% if forloop.last and not archive %}
          <p>
            <a href="{% url 'posts:group_archive' post.group.slug %}"> Архив группы </a>
          </p>
        {% endif %}

      </article>

        {% if not forloop.last %}
            <hr>
        {% endif %}

    {% endfor %}

      <p>
        <a href="{% url 'posts:index' %}"> Возврат на главную страницу </a>
      </p>

{% endblock %}

posts/templates/posts/index.html
<!-- templates/posts/index.html -->

{% extends 'base.html' %}

{% block title %}
  Главная страница
{% endblock %}

{% block content %}



    {% for post in page_obj %}

      <article>

        {% include 'includes/fullpost.html' %}

      </article>

      {% if not loop.last %}
        <hr>
      {% endif %}

    {% endfor %}

    {% if not follow %}
        <p>
          <a href="{{ url_for('posts.group_list') }}"> Список всех групп </a>
        </p>
    {% endif %}
        {% include 'includes/custom_paginator.html' %}
{% endblock %}

posts/templates/posts/list_of_groups.html
<!-- templates/posts/list_of_groups.html -->

{% extends 'base.html' %}

{% block title %}
  Список всех групп
{% endblock %}

{% block content %}

    <h2> Список всех групп </h2>
    <ol>
      {% for group in groups %}
        <li>
          <h4>
              {{ group }}
          </h4>
          <h5>
              <a href="{{ url_for('posts.post_group', group_slug=group.slug) }}"> Архив группы </a>
          </h5>
        </li>
      {% endfor %}
    </ol>
      <p>
        <a href="{{ url_for('posts.index') }}"> Возврат на главную страницу </a>
      </p>

{% endblock %}

posts/templates/posts/post_confirm_delete.html
<!-- templates/posts/includes/post_confirm_delete.html -->

{% extends 'base.html' %}

{% block title %}
    Удаление поста
{% endblock %}

{% block content %}

    <form method="post">
        {% csrf_token %}
{# Тут должен был быть заголовок#}
{#        <p>#}
{#            Вы уверены, что хотите удалить пост "{{ object.title }}"?#}
{#        </p>#}

        <p>
            Вы уверены, что хотите удалить пост "{{ object.id }}"?
        </p>

        <input type="submit" value="Да, уверен">

    </form>

{% endblock %}

posts/templates/posts/show_post.html
<!-- templates/posts/show_post.html -->

{% extends 'base.html' %}



{% block title %}
  Страница поста {{ post.id }}
{% endblock %}

{% block content %}

  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">

        {# Название поста #}
        <li class="list-group-item">
          Название: <b>{{ post.title }}</b>
        </li>

        <li class="list-group-item">
          Рейтинг: <b>{{ rating }}</b>
        </li>

        <li class="list-group-item">
          Дата публикации: {{ post.created.strftime('%Y-%m-%d') }}
        </li>

        <li class="list-group-item">
            {% if post.group %}
                <p>Группа: {{ post.group }}</p>
                <p>
                  <a href="{{ url_for('posts.group_list', group_slug=post.group.slug) }}"> Все записи группы {{ post.group.slug }} </a>
                </p>
            {% else %}
              <p> Группа отсутствует </p>
            {% endif %}
        </li>

        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>

        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ 1 }}</span>
        </li>

        <li class="list-group-item">
          <a href="{{ url_for('users.show_profile', user_slug=1) }}">
            все посты пользователя
          </a>
        </li>

      </ul>
    </aside>
    <article class="col-12 col-md-9">

      <div style="padding-left:0px">
          <div style="padding-bottom:20px">
<!--  Вставка картинки  -->
          </div>
      </div>

      <p>
          {{ post.text }}
      </p>

<!--        Проверка на авторизацию -->





    </article>

    <div class="container py-5">
      <div class="row justify-content-center">

<!--          форма комментариев -->


      </div>
    </div>
    <hr>
    <div style="padding-bottom:30px">

        {% if not comments_count %}
            <h3>Комментарии к посту отсутствуют</h3>
        {% else %}
            <h3>Комментариев к посту: {{ comments_count }}</h3>
        {% endif %}

    </div>



  </div>

{% endblock %}

posts/templates/posts/show_post_old.html
<!-- templates/posts/show_post.html -->

{% extends 'base.html' %}

{% load thumbnail %}

{% block title %}
  Страница поста {{ post.id }}
{% endblock %}

{% block content %}

  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">

        {# Название поста #}
        <li class="list-group-item">
          Название: <b>{{ post.title }}</b>
        </li>

        <li class="list-group-item">
          Рейтинг: <b>{{ rating }}</b>
        </li>

        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>

        <li class="list-group-item">
            {% if post.group %}
                <p>Группа: {{ post.group }}</p>
                <p>
                  <a href="{% url 'posts:group_list' post.group.slug %}"> Все записи группы {{ post.group.slug }} </a>
                </p>
            {% else %}
              <p> Группа отсутствует </p>
            {% endif %}
        </li>

        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>

        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ post.author.posts.count }}</span>
        </li>

        <li class="list-group-item">
          <a href="{% url 'posts:show_profile' post.author %}">
            все посты пользователя
          </a>
        </li>

      </ul>
    </aside>
    <article class="col-12 col-md-9">

      <div style="padding-left:0px">
          <div style="padding-bottom:20px">
            {% thumbnail post.image "1280x1024" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
            {% endthumbnail %}
          </div>
      </div>

      <p>
          {{ post.text|linebreaksbr }}
      </p>

      {% if request.user.is_authenticated %}

          <div style="padding-bottom:40px">
              <p align="right">
                  {% if request.user == post.author %}
                    <a class="btn btn-primary"  href="{% url 'posts:post_edit' post.id %}">
                      Редактировать пост
                    </a>
                    <a class="btn btn-primary"  href="{% url 'posts:post_delete' post.id %}">
                      Удалить пост
                    </a>
                  {% else %}

                    <a class="btn btn-primary" href="{% url 'posts:post_comment' post.id %}">
                      Комментировать пост
                    </a>

                    <a class="btn btn-primary" href="{% url 'posts:post_like' post.id %}">
                      Лайк
                    </a>

                    <a class="btn btn-primary" href="{% url 'posts:post_dislike' post.id %}">
                      Дизлайк
                    </a>
                  {% endif %}
              </p>
          </div>

      {% endif %}


    </article>

    <div class="container py-5">
      <div class="row justify-content-center">

        {% include 'includes/form.html' with is_comment=True %}

      </div>
    </div>
    <hr>
    <div style="padding-bottom:30px">

        {% if not comments_count %}
            <h3>Комментарии к посту отсутствуют</h3>
        {% else %}
            <h3>Комментариев к посту: {{ comments_count }}</h3>
        {% endif %}

    </div>

      {% for comment in object_list %}

        <article class="align-content-lg-around">
            <div class="card mb-4">

                <li class="list-group-item ">
                    <div class="card-header">
                      <p>Автор комментария: <b>{{ comment.author }}</b></p>
                    </div>
                    <div class="card-body">
                      <p>
                          <b>Сообщение</b>: {{ comment.text|linebreaksbr|truncatewords:30 }}
                      </p>

                      {% if comment.image %}
                        <img class="img-fluid" width="500" height="600" src="{{ comment.image.url }}">
                      {% endif %}

                    </div>
                </li>

            </div>

            {% if request.user.is_authenticated %}
                <p align="right">
                    {# Добавить выпадающий список комментариев #}
                    {% if smth %}
                        <a class="btn btn-info" href="">
                            Раскрыть
                        </a>
                    {% endif %}

                    <a class="btn btn-info" href="{% url 'posts:comment_comment' post.id comment.id %}">
                        Комментировать
                    </a>

                    {% if request.user == comment.author %}
                        <a class="btn btn-info" href="{% url 'posts:post_comment_edit' post.id comment.id %}">
                            Редактировать
                        </a>

                    {% endif %}
                </p>
            {% endif %}

            {# Обращение вида treads.comment.id не отработает #}
            {% for key, value in treads.items %}
                {% if key == comment.id %}

                    <div style="padding-left:40px">
                        {% for child_comment in value %}

                            <li class="list-group-item ">

                              <p>Автор комментария: <b>{{ child_comment.author }}</b></p>

                              <p><b>Сообщение</b>: {{ child_comment.text|linebreaksbr|truncatewords:30 }}</p>

                              {% if child_comment.image %}
                                <img class="img-fluid" width="500" height="600" src="{{ child_comment.image.url }}">
                              {% endif %}

                            </li>

                            {% if request.user == child_comment.author %}
                                <p align="right">
                                    <a class="btn btn-info" href="{% url 'posts:post_comment_edit' post.id child_comment.id %}">
                                        Редактировать
                                    </a>
                                </p>
                            {% endif %}

                        {% endfor %}
                    </div>

                {% endif %}
            {% endfor %}

        </article>
      {% endfor %}

  </div>

{% endblock %}